# Generated by Django 5.1.1 on 2024-09-10 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_company_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exhibition',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
